#!/bin/bash

set -x

echo "$@"

if [ "$1" = "get-site-id" ]; then
  echo "Fetching site ID..."
  echo "ga-bu-zo-meu" > /site_id
elif [ "$1" = "deploy" ]; then
  echo "Deploying..."
  echo '{"url": "http://localhost:4242/mysite"}' > /deploy_result
fi
